version: "3"
services:

  postgres:
    image: "postgres:14.0"
    environment:
      - POSTGRES_USER=demoshop
      - POSTGRES_PASSWORD=topsecret
    ports:
      - "65432:5432"

  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    depends_on:
      - postgres
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - DB_USER=demoshop
      - DB_PASSWORD=topsecret
      - DB_HOST=postgres
      - DB_PORT=5432
      - API_PORT=8000

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    depends_on:
      - api
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - API_HOST=api
      - API_PORT=8000
    ports:
      - "3000:3000"
