version: "3"
services:

  postgres:
    image: "postgres:14.0"
    environment:
      - POSTGRES_USER=demoshop
      - POSTGRES_PASSWORD=topsecret
    ports:
      - "65432:5432"

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    depends_on:
      - postgres
    environment:
      - DB_USER=demoshop
      - DB_PASSWORD=topsecret
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=demoshop
      - API_PORT=8000
    ports:
      - "8000:8000"

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    depends_on:
      - backend
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
    ports:
      - "3000:3000"
